server:
  port: 8082
  servlet:
    context-path: /event-registration-service

spring:
  application:
    name: EVENT-REGISTRATION-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ems
    username: postgres
    password: Aspire123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
